on: [push]

jobs:
  oquare_metrics:
    runs-on: ubuntu-latest
    name: OQuaRE-metrics-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Basic testing
        uses: ./
        with:
          ontology-files: ontologies/imports/obi.owl
